# Generated by Django 5.1.5 on 2025-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('author', models.CharField(max_length=100)),
                ('publishedDate', models.DateField()),
                ('numberOfPages', models.IntegerField()),
            ],
        ),
    ]
