# Generated by Django 5.1.5 on 2025-02-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Book',
        ),
    ]
