# Generated by Django 5.1.5 on 2025-02-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
